version: '3.8'

services:
  
  backend:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: Backend
    ports:
      - "5285:5285"
      - "7272:7272"
    environment:
      - ASPNETCORE_URLS=https://+:7272;http://+:5285
      - POSTGRES_USER=zeiad
      - POSTGRES_PASSWORD=12345
      - ConnectionStrings__PostgreSql=Host=postgres;Port=5432;Database=mydatabase;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    volumes:
      - C:\Users\zeiad\source\repos\Yossifemad19\SportsReservationSystemGp\published:/app
    working_dir: /app
    command: ["dotnet", "backend.Api.dll"]
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
